# Form implementation generated from reading ui file '/home/nozwock/hub/dev/repo/spotdl_gui/spotdl_gui/views/about.ui'
#
# Created by: PySide6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(300, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(About)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_about = QtWidgets.QLabel(parent=About)
        self.label_about.setObjectName("label_about")
        self.verticalLayout.addWidget(self.label_about)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=About)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(About)
        self.buttonBox.accepted.connect(About.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About"))
        self.label_about.setText(_translate("About", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">spotDL GUI</span></p><p align=\"center\"><span style=\" font-size:12pt;\">Version: %version%</span></p><p align=\"center\"><span style=\" font-size:12pt;\">spotDL: %spotdlversion%</span></p><p align=\"center\"><a href=\"https://github.com/nozwock/spotdl_gui\"><span style=\" font-size:12pt;text-decoration: underline; color:#007af4;\">Repository</span></a><span style=\" font-size:12pt;\"> on GitHub </span></p></body></html>"))
