# Form implementation generated from reading ui file '/home/nozwock/hub/dev/repo/spotdl_gui/spotdl_gui/views/about.ui'
#
# Created by: PySide6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(300, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(About)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=About)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=About)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About"))
        self.label.setText(_translate("About", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">SpotDL GUI</span></p><p align=\"center\"><span style=\" font-size:12pt;\">Version: %version%</span></p><p align=\"center\"><span style=\" font-size:12pt;\">Repository: </span><a href=\"https://github.com/nozwock/spotdl_gui\"><span style=\" text-decoration: underline; color:#007af4;\">GitHub</span></a></p></body></html>"))
