# Form implementation generated from reading ui file 'spotdl_gui/views/mainwindow.ui'
#
# Created by: PySide6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_search = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_search.setMinimumSize(QtCore.QSize(125, 0))
        self.lineEdit_search.setText("")
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout.addWidget(self.lineEdit_search)
        self.pushButton_search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout.addWidget(self.pushButton_search)
        self.comboBox_filter = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_filter.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_filter.setObjectName("comboBox_filter")
        self.comboBox_filter.addItem("")
        self.comboBox_filter.addItem("")
        self.comboBox_filter.addItem("")
        self.comboBox_filter.addItem("")
        self.comboBox_filter.addItem("")
        self.comboBox_filter.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_filter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.columnView = QtWidgets.QColumnView(parent=self.centralwidget)
        self.columnView.setEnabled(True)
        self.columnView.setObjectName("columnView")
        self.verticalLayout_2.addWidget(self.columnView)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(600, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_lyrics = QtWidgets.QComboBox(parent=self.widget)
        self.comboBox_lyrics.setObjectName("comboBox_lyrics")
        self.comboBox_lyrics.addItem("")
        self.comboBox_lyrics.addItem("")
        self.comboBox_lyrics.addItem("")
        self.comboBox_lyrics.addItem("")
        self.comboBox_lyrics.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_lyrics)
        self.comboBox_format = QtWidgets.QComboBox(parent=self.widget)
        self.comboBox_format.setObjectName("comboBox_format")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_format)
        self.comboBox_bitrate = QtWidgets.QComboBox(parent=self.widget)
        self.comboBox_bitrate.setObjectName("comboBox_bitrate")
        self.comboBox_bitrate.addItem("")
        self.comboBox_bitrate.addItem("")
        self.comboBox_bitrate.addItem("")
        self.comboBox_bitrate.addItem("")
        self.comboBox_bitrate.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_bitrate)
        self.toolButton = QtWidgets.QToolButton(parent=self.widget)
        icon = QtGui.QIcon.fromTheme("folder")
        self.toolButton.setIcon(icon)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_download = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_download.setObjectName("pushButton_download")
        self.verticalLayout.addWidget(self.pushButton_download)
        self.verticalLayout_2.addWidget(
            self.widget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter
        )
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 600, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(parent=self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionOpen_SpotDL_config_folder = QtGui.QAction(parent=MainWindow)
        self.actionOpen_SpotDL_config_folder.setObjectName(
            "actionOpen_SpotDL_config_folder"
        )
        self.actionSettings = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/icons/bx-cog.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.actionSettings.setIcon(icon)
        self.actionSettings.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionSettings.setObjectName("actionSettings")
        self.actionDownload = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/icons/bx-download.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.actionDownload.setIcon(icon1)
        self.actionDownload.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionDownload.setObjectName("actionDownload")
        self.actionExport = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/icons/bxs-file-export.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.actionExport.setIcon(icon2)
        self.actionExport.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionExport.setObjectName("actionExport")
        self.actionImport = QtGui.QAction(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/icons/bxs-file-import.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.actionImport.setIcon(icon3)
        self.actionImport.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionImport.setObjectName("actionImport")
        self.menuFile.addAction(self.actionOpen_SpotDL_config_folder)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addAction(self.actionImport)
        self.toolBar.addAction(self.actionExport)
        self.toolBar.addAction(self.actionDownload)

        self.retranslateUi(MainWindow)
        self.comboBox_filter.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_search.setPlaceholderText(
            _translate("MainWindow", "Search for music or paste link here...")
        )
        self.pushButton_search.setText(_translate("MainWindow", "Search"))
        self.comboBox_filter.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Filter</p></body></html>")
        )
        self.comboBox_filter.setItemText(0, _translate("MainWindow", "Liked Songs"))
        self.comboBox_filter.setItemText(
            1, _translate("MainWindow", "All User Playlists")
        )
        self.comboBox_filter.setItemText(2, _translate("MainWindow", "Playlists"))
        self.comboBox_filter.setItemText(3, _translate("MainWindow", "Album"))
        self.comboBox_filter.setItemText(4, _translate("MainWindow", "Songs"))
        self.comboBox_filter.setItemText(5, _translate("MainWindow", "Query"))
        self.comboBox_lyrics.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Lyrics</p></body></html>")
        )
        self.comboBox_lyrics.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_lyrics.setItemText(1, _translate("MainWindow", "genius"))
        self.comboBox_lyrics.setItemText(2, _translate("MainWindow", "musixmatch"))
        self.comboBox_lyrics.setItemText(3, _translate("MainWindow", "azlyrics"))
        self.comboBox_lyrics.setItemText(4, _translate("MainWindow", "synced"))
        self.comboBox_format.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Format</p></body></html>")
        )
        self.comboBox_format.setItemText(0, _translate("MainWindow", "mp3"))
        self.comboBox_format.setItemText(1, _translate("MainWindow", "flac"))
        self.comboBox_format.setItemText(2, _translate("MainWindow", "ogg"))
        self.comboBox_format.setItemText(3, _translate("MainWindow", "opus"))
        self.comboBox_format.setItemText(4, _translate("MainWindow", "m4a"))
        self.comboBox_format.setItemText(5, _translate("MainWindow", "wav"))
        self.comboBox_bitrate.setToolTip(
            _translate("MainWindow", "<html><head/><body><p>Bitrate</p></body></html>")
        )
        self.comboBox_bitrate.setItemText(0, _translate("MainWindow", "auto"))
        self.comboBox_bitrate.setItemText(1, _translate("MainWindow", "disable"))
        self.comboBox_bitrate.setItemText(2, _translate("MainWindow", "8k"))
        self.comboBox_bitrate.setItemText(3, _translate("MainWindow", "16k"))
        self.comboBox_bitrate.setItemText(4, _translate("MainWindow", "24k"))
        self.toolButton.setToolTip(
            _translate(
                "MainWindow",
                "<html><head/><body><p>Pick output folder</p></body></html>",
            )
        )
        self.toolButton.setText(_translate("MainWindow", "Browse"))
        self.pushButton_download.setText(_translate("MainWindow", "Download"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen_SpotDL_config_folder.setText(
            _translate("MainWindow", "Open SpotDL Config Folder")
        )
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionDownload.setText(_translate("MainWindow", "Download"))
        self.actionDownload.setToolTip(_translate("MainWindow", "Download selected"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionExport.setToolTip(
            _translate("MainWindow", "Export fetched song list to a file")
        )
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionImport.setToolTip(
            _translate("MainWindow", "Import exported songs list")
        )
